version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ecomess_postgres
    environment:
      POSTGRES_USER: ecomess
      POSTGRES_PASSWORD: ecomess_password
      POSTGRES_DB: ecomess_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ecomess"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: